### ISSUE TITLE
backend: セッションの確立回り

### ISSUE THREAD

**Issue by iorar** [85yago/go_small_chat#13]
main.goとは分けてwebsocket周辺をしばいてほしい
クライアントとの通信を行う部分

**Comment by 85yago** [comment]
https://hoohoo.top/blog/20220320172715-go-websocket/
https://blog.narumium.net/2019/07/11/%E3%80%90go%E3%80%91websocket%E3%81%AB%E3%82%88%E3%82%8B%E9%80%9A%E4%BF%A1/
https://qiita.com/tashxii/items/75b99c32b024a1c06eb7
この辺見ればよさそう

**Comment by 85yago** [comment]
https://developer.mozilla.org/ja/docs/Web/API/WebSockets_API/Writing_WebSocket_servers

**Comment by 85yago** [comment]
https://zenn.dev/hsaki/books/golang-concurrency/viewer/intro

**Comment by iorar** [comment]
post,getを実装するときにいじるのでissueは残しておきます
