### ISSUE TITLE
問題: postgresqlのdbの保存先の調査&変更

### ISSUE THREAD

**Issue by iorar** [85yago/go_small_chat#15]
予定通りdb_data配下に設置したい

**Comment by 85yago** [comment]
docker-compose.yaml直下のvolumesにdb_dataと書いてdbのvolumesにつなげていた。
これはdockerが名前付きvolumeを作成して保存しているので、db_dataフォルダは使われなかった。

dbのvolumesのホストOS側をちゃんとパスとして書くことで保存されるようになった。
ポスグレの初期保存先は/var/lib/postgres/dataなのでこれにdb_dataフォルダを繋げた。
この時、db_dataに何か入っているとdbコンテナが立ち上がらない。
docker-composeが勝手にvolumesに指定しているファイルを作ってくれるのでdb_dataフォルダはgit下から外した。

**Comment by 85yago** [comment]
https://qiita.com/at_sushi/items/04a84193fb6c7076e86f
