### ISSUE TITLE
Other: 開発向けのスクリプトが欲しい

### ISSUE THREAD

**Issue by iorar** [85yago/go_small_chat#17]
db_dataをいちいち削除するのが面倒なのでテスト用のコンテナ再生成スクリプトを生やしたい気がしています,特に必要性が無さそうならやめます
.shにまとめるだけなら簡単そう

**Comment by 85yago** [comment]
コンテナを再生成したいことってかなりあったっけ

**Comment by 85yago** [comment]
りかい
https://www.postgresql.org/docs/current/functions-sequence.html
https://www.t-webu.net/postgres/postgres%E3%81%AB%E3%81%A6%E3%82%B7%E3%83%BC%E3%82%B1%E3%83%B3%E3%82%B9%E3%82%92%E3%83%AA%E3%82%BB%E3%83%83%E3%83%88%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95.html
IDの採番がリセットされないからこれをリセットしたかった。
オートインクリメントのIDとかは特殊なテーブルが生える。こいつの中をいじることで修正可能。
テスト用にコードを追加した。
