### ISSUE TITLE
Other: テスト用スクリプトの削除

### ISSUE THREAD

**Issue by iorar** [85yago/go_small_chat#20]
全部おわったらテスト用スクリプトを破棄しよう
コメントアウトで　`//TODO: xxx...` と記述しておくこと

削除メモ：
- idの採番をリセットしている部分 (dbinit.go)

**Comment by 85yago** [comment]
ginをリリースモードにしないといけない。

**Comment by 85yago** [comment]
マージしたので閉じ。
