### ISSUE TITLE
Other: アプリの置き場とか

### ISSUE THREAD

**Issue by 85yago** [85yago/go_small_chat#34]
docker-composeを叩けば（たぶん）動くが、どこに置いておこう。
vercel？ラズパイ？

**Comment by 85yago** [comment]
僕の余っているOCIのインスタンスに乗せる。

**Comment by 85yago** [comment]
先にSSL化ができるかをしとく必要がありそう。

**Comment by iorar** [comment]
インスタンスに乗り次第閉じる形で。

**Comment by 85yago** [comment]
マージしたので閉じ。
