### ISSUE TITLE
Other: SSL化をしよう

### ISSUE THREAD

**Issue by 85yago** [85yago/go_small_chat#35]
SSLに対応しないと大体のブラウザに怒られる。
とりあえずはLet's Encryptでよさそう。
https://letsencrypt.org/

**Comment by 85yago** [comment]
https://pkg.go.dev/golang.org/x/crypto/acme/autocert?utm_source=godoc
これでよさそう。WSも同じ方法で対応できるかが不明。

**Comment by 85yago** [comment]
https://passe-de-mode.uedasoft.com/ja/tips/software/unclassified/go/go03.html
https://qiita.com/kjm/items/292f6f262891c60fcaa2
参考に。

**Comment by 85yago** [comment]
WSもほぼ同様っぽい。
https://stackoverflow.com/questions/61324875/websocket-over-tls-golang-gorilla
https://pkg.go.dev/github.com/gin-gonic/gin#Engine.RunTLS
これを叩けば良さそう。

**Comment by 85yago** [comment]
ちゃんと動いてhttpsでアクセスできるのを確認済み。
ローカルで動かせるようにしたい。
方法としては、
- コードを環境変数などで分岐させる
- リリースを使う（？）
など。分岐させるのが手っ取り早そう。

**Comment by iorar** [comment]
ローカルではテスト出来なさそうなのでテスト機能を使っていきたいところ。

**Comment by iorar** [comment]
一応調べるとlocalhostにオレオレ証明書をくっつけてオレオレ証明書を信用してる発行者リストに追記する方法なんかがあるみたい
とはいえあまりローカルの環境を破壊したくないので、やっぱりテストでがんばるのが無難そうですね

**Comment by 85yago** [comment]
テスト機能を使ってもautocert周りのコードはどうせ動かないので、コードを分岐させる方向で行きたい。
.envに書いておくとかでよいかな？

**Comment by 85yago** [comment]
```go
    MODE := os.Getenv("WORKING_MODE")
    if MODE == "RELEASE" {

    } else if MODE == "DEBUG" {

    } else {

    }
```
こんな感じで分岐をさせる。

**Comment by 85yago** [comment]
結局build tagを使った。

マージしたので閉じ。
