### ISSUE TITLE
frontend: テスト用のフロント実装

### ISSUE THREAD

**Issue by iorar** [85yago/go_small_chat#6]
APIを全種類叩けるフロント側の実装
①postMessageでメッセージを送れる
②getMessageで最新メッセージを一定件数受け取り表示できる

**Comment by 85yago** [comment]
メッセージをある程度溜まったら消したい。100件とか。

**Comment by 85yago** [comment]
wsが切れたら再接続したい。何回か試行。
繋がらなかった時とかもなんかしときたいかも。

**Comment by 85yago** [comment]
どっちも書いた。
繋がらなかった時のはどうしとこうね。

**Comment by 85yago** [comment]
死んだままでよし。またあとでなんとかする。
マージしたので閉じ。
