### ISSUE TITLE
db: スキーマの生成

### ISSUE THREAD

**Issue by iorar** [85yago/go_small_chat#7]
db用のスキーマを"db"ディレクトリ配下に生成する。GoのGORMの仕様に準拠すること。

**Comment by 85yago** [comment]
https://gorm.io/ja_JP/docs/migration.html
https://gorm.io/ja_JP/docs/index.html
https://qiita.com/chan-p/items/cf3e007b82cc7fce2d81

**Comment by 85yago** [comment]
https://future-architect.github.io/articles/20210728a/

**Comment by iorar** [comment]
スキーマを整備したのでクローズしまつ
